MODEL:
  NAME: "inception_v3"
DATASET:
  NAME: "CUB"
  ROOT_DIR: "datasets"
  PREPROCESS: "cbm"
OPTIM:
  LR: 1e-3
  EPOCHS: 200
  BATCH_SIZE: 64
  STEP_SIZE: 50
  GAMMA: 0.5
  WEIGHT_DECAY: 0.0004
SEED: 42