MODEL:
  BACKBONE:
    NAME: "inception_v3"
    CKPT_PATH: ""
  LOSSES:
    L_C: 0.01
    L_Y: 1
DATASET:
  NAME: "CUB"
  NUM_ATTRS: 112
  ROOT_DIR: "datasets"
  PREPROCESS: "cbm"
OPTIM:
  LR: 1e-3
  EPOCHS: 20
  BATCH_SIZE: 64
  STEP_SIZE: 15
  GAMMA: 0.5
  WEIGHT_DECAY: 0.0004
SEED: 42