MODEL:
  NAME: "dev_resnet50"
  ACTIVATION: None
  BACKBONE: "resnet50"
  USE_SIGMOID: True
  USE_ATTENTION: False
  LOSSES:
    L_C: 1e-2
    L_Y: 1
    L_CPT: 1e-3
    USE_ATTR_WEIGHTS: False
DATASET:
  NAME: "CUB"
  NUM_ATTRS: 112
  ROOT_DIR: "datasets"
  USE_ATTRS: "data/cub/attributes.txt"
  USE_ATTR_MASK: "data/cub/attribute_names_mask.txt"
  USE_SPLITS: "data/cub/split_image_ids.npz"
OPTIM:
  LR: 1e-3
  EPOCHS: 500
  BATCH_SIZE: 64
  WEIGHT_DECAY: 4e-4
SEED: 42