MODEL:
  NAME: "dev_resnet101"
  BACKBONE: "resnet101"
  USE_ATTENTION: False
  LOSSES:
    L_C: 1e-1
    L_Y: 1
    L_CPT: 1e-3
    USE_ATTR_WEIGHTS: False
DATASET:
  NAME: "CUB"
  NUM_ATTRS: 312
  ROOT_DIR: "datasets"
  USE_ATTRS: "binary"
  USE_ATTR_MASK: False
  USE_SPLITS: "data/cub/split_image_ids.npz"
#  AUGMENTATION: "crop"
  CROP: False
OPTIM:
  OPTIMIZER: SGD
  LR: 1e-3
  EPOCHS: 200
  BATCH_SIZE: 64
  WEIGHT_DECAY: 4e-4
  EARLY_STOP: 30
SEED: 42