MODEL:
  NAME: "dev_resnet101"
  ACTIVATION: None
  BACKBONE: "resnet101"
  LOSSES:
    L_C: 1e-2
    L_Y: 1
    L_CPT: 1e-3
DATASET:
  NAME: "CUB"
  NUM_ATTRS: 112
  ROOT_DIR: "datasets"
  USE_ATTRS: "data/cub/attributes.txt"
  USE_ATTR_MASK: "data/cub/attribute_names_mask.txt"
  USE_SPLITS: "data/cub/split_image_ids.npz"
OPTIM:
  LR_BACKBONE: 1e-4
  LR: 1e-3
  EPOCHS: 50
  BATCH_SIZE: 64
  STEP_SIZE: 5
  GAMMA: 0.2
  WEIGHT_DECAY: 4e-4
SEED: 42